[package]
name = "dumbarpd"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum = "0.8.9"
clap = { workspace = true, features = ["derive"] }
dumbarp = { version = "0.1.0", path = "../dumbarp" }
futures = "0.3"
libc.workspace = true
mozim = "0.2.3"
dumbarp-routing = { path = "../dumbarp-routing" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { workspace = true, features = ["full"] }
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
dumbarp-api = { version = "0.1.0", path = "../dumbarp-api" }
dumbarp-common = { version = "0.1.0", path = "../dumbarp-common" }

[package.metadata.deb]
name = "dumbarpd"
maintainer = "Allen <mail@drchi.co.kr>"
copyright = "2026, Allen"
license-file = "../LICENSE-MIT"
extended-description = "XDP-based ARP responder daemon with a REST control API."
depends = "$auto"
section = "net"
priority = "optional"
assets = [
    ["target/release/dumbarpd", "usr/bin/", "755"],
    ["debian/config.example.toml", "etc/dumbarpd.toml", "640"],
]
conf-files = ["/etc/dumbarpd.toml"]
maintainer-scripts = "debian/"
systemd-units = { unit-name = "dumbarpd", enable = true, start = true, restart-after-upgrade = true }
